### ISSUE TITLE
改个项目名字吧

### ISSUE THREAD

**Issue by txyyss** [lexrus/fontdiao#11]
用这么不雅的字作为项目名称，会让有心贡献的人都避之不及啊。

**Comment by lexrus** [comment]
“屌” 在这里是 “厉害” 的意思。
这个项目只是一个小工具，我认为工具最重要的一个特性就是好使，而不是有优雅的名字。
锤子也有骂人的意思，可它还是叫锤子。

如果你有心贡献，但又介意这个名字，你可以 fork 后换一个名字，然后号召大家都去你的改名后的 repo 做贡献，WTFPL 协议允许你这样做。

**Comment by tioover** [comment]
赞

**Comment by samluthebrave** [comment]
这名字是向FontAwesome致敬吗？哈哈。
