### ISSUE TITLE
可以加入虾米音乐吗？

### ISSUE THREAD

**Issue by skovely** [lexrus/fontdiao#16]
可以新增国内的各大互联网音乐的icon吗？如虾米音乐，网易云音乐、qq音乐

**Comment by lexrus** [comment]
虾米的 icon 是那根蟹爪吗？其它两个服务我都没用过，能麻烦你把图标地址贴过来吗？

**Comment by skovely** [comment]
你看下面的图可以用么？

虾米：
http://img.xiami.net/favicon.ico  
http://img0.weixinla.com/weixin/avatar/20130304/5dd39130408771cb9e084e4f6e0f5dda.png （个人觉得这个可能更好看一些）
http://images.liqucn.com/h006/h89/img201305021756020.png

豆瓣FM：
http://douban.fm/favicon.ico 
http://img2.91huo.cn/mm/2012/06/21/dbfm.jpg

网易云音乐：
http://weixin111.com/uploads/201308/2013822105052287.jpg

QQ音乐：
http://y.qq.com/favicon.ico
http://cdn.marketplaceimages.windowsphone.com/v8/images/901525b5-b449-4f18-b0c1-6990d9a721e3?imageType=ws_icon_large

**Comment by lexrus** [comment]
豆瓣的这个认知度太低啦，尤其是做成黑白之后。

**Comment by skovely** [comment]
恩，也是，黑白的就成一坨看不出来了

**Comment by lexrus** [comment]
除了豆瓣的，都加上了。你可以在这里看一下：
http://lexrus.github.io/fontdiao/

**Comment by skovely** [comment]
赞一个，非常感谢啦
