### ISSUE TITLE
可以问下这么好的项目为什么废弃呢？

### ISSUE THREAD

**Issue by qiansen1386** [lexrus/fontdiao#18]
您好
可以问一下您，这么好的项目为什么要废弃么？
还有就是，如果废弃已无法避免，请问您知道有其他能比得上您这个项目的替代项目么？

**Comment by lexrus** [comment]
你好。
我现在不做前端相关的工作了，没有精力维护这个项目。
阿里做的那个不错，你可以试试：
http://iconfont.cn
