### ISSUE TITLE
CSS3111: @font-face encountered unknown error

### ISSUE THREAD

**Issue by JoshuaChi** [lexrus/fontdiao#7]
CSS3111: @font-face encountered unknown error.
fontdiao,eot?#iefix&v=0.06

--- when testing with IE9

**Comment by lexrus** [comment]
Sigh, I don't have a PC with IE9 installed.
Could you be a little more specific? Which icon did you use? Does this issue also occurs in IE10?

**Comment by JoshuaChi** [comment]
When using "icon-weibo".

I don't have ie10 installed. But it seems working with ie8(win7).

**Comment by lexrus** [comment]
Could you please try the latest version(0.0.7) ?
